### ISSUE TITLE
Miniconda setup error

### ISSUE THREAD

**Issue by ma-sadeghi** [conda-incubator/setup-miniconda#180]
Reference: https://github.com/PMEAL/OpenPNM/actions/runs/968168785

```bash
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/share/miniconda/lib/python3.8/site-packages/urllib3/response.py", line 436, in _error_catcher
        yield
      File "/usr/share/miniconda/lib/python3.8/site-packages/urllib3/response.py", line 763, in read_chunked
        self._update_chunk_length()
      File "/usr/share/miniconda/lib/python3.8/site-packages/urllib3/response.py", line 693, in _update_chunk_length
        line = self._fp.fp.readline()
      File "/usr/share/miniconda/lib/python3.8/socket.py", line 669, in readinto
        return self._sock.recv_into(b)
      File "/usr/share/miniconda/lib/python3.8/ssl.py", line 1241, in recv_into
        return self.read(nbytes, buffer)
      File "/usr/share/miniconda/lib/python3.8/ssl.py", line 1099, in read
        return self._sslobj.read(len, buffer)
    ConnectionResetError: [Errno 104] Connection reset by peer
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/share/miniconda/lib/python3.8/site-packages/requests/models.py", line 751, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "/usr/share/miniconda/lib/python3.8/site-packages/urllib3/response.py", line 571, in stream
        for line in self.read_chunked(amt, decode_content=decode_content):
      File "/usr/share/miniconda/lib/python3.8/site-packages/urllib3/response.py", line 792, in read_chunked
        self._original_response.close()
      File "/usr/share/miniconda/lib/python3.8/contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/share/miniconda/lib/python3.8/site-packages/urllib3/response.py", line 454, in _error_catcher
        raise ProtocolError("Connection broken: %r" % e, e)
    urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/share/miniconda/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/usr/share/miniconda/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/usr/share/miniconda/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/usr/share/miniconda/lib/python3.8/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/usr/share/miniconda/lib/python3.8/site-packages/conda/cli/install.py", line 261, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/usr/share/miniconda/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/usr/share/miniconda/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/usr/share/miniconda/lib/python3.8/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/usr/share/miniconda/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/usr/share/miniconda/lib/python3.8/site-packages/conda/core/solve.py", line 425, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/usr/share/miniconda/lib/python3.8/site-packages/conda/core/solve.py", line 1020, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/usr/share/miniconda/lib/python3.8/site-packages/conda/core/index.py", line 276, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "/usr/share/miniconda/lib/python3.8/site-packages/conda/core/subdir_data.py", line 120, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/usr/share/miniconda/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
        yield fs.pop().result()
      File "/usr/share/miniconda/lib/python3.8/concurrent/futures/_base.py", line 439, in result
        return self.__get_result()
      File "/usr/share/miniconda/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
        raise self._exception
      File "/usr/share/miniconda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/share/miniconda/lib/python3.8/site-packages/conda/core/subdir_data.py", line 112, in <lambda>
        subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
      File "/usr/share/miniconda/lib/python3.8/site-packages/conda/core/subdir_data.py", line 125, in query
        self.load()
      File "/usr/share/miniconda/lib/python3.8/site-packages/conda/core/subdir_data.py", line 189, in load
        _internal_state = self._load()
      File "/usr/share/miniconda/lib/python3.8/site-packages/conda/core/subdir_data.py", line 259, in _load
        raw_repodata_str = fetch_repodata_remote_request(
      File "/usr/share/miniconda/lib/python3.8/site-packages/conda/core/subdir_data.py", line 499, in fetch_repodata_remote_request
        resp = session.get(join_url(url, filename), headers=headers, proxies=session.proxies,
      File "/usr/share/miniconda/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
        return self.request('GET', url, **kwargs)
      File "/usr/share/miniconda/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/share/miniconda/lib/python3.8/site-packages/requests/sessions.py", line 685, in send
        r.content
      File "/usr/share/miniconda/lib/python3.8/site-packages/requests/models.py", line 829, in content
        self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
      File "/usr/share/miniconda/lib/python3.8/site-packages/requests/models.py", line 754, in generate
        raise ChunkedEncodingError(e)
    requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

`$ /usr/share/miniconda/condabin/conda install --name base mamba=*`

  environment variables:
                 CIO_TEST=<not set>
                    CONDA=/usr/share/miniconda
           CONDA_PKGS_DIR=/home/runner/conda_pkgs_dir
               CONDA_ROOT=/usr/share/miniconda
           CURL_CA_BUNDLE=<not set>
      DEPLOYMENT_BASEPATH=/opt/runner
        GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json
              GITHUB_PATH=/home/runner/work/_temp/_runner_file_commands/add_path_9c73a400-b1a4-4
                          d6e-829b-30f49e9129a1
          LD_LIBRARY_PATH=/opt/hostedtoolcache/Python/3.8.10/x64/lib
                     PATH=/usr/share/miniconda/condabin:/opt/hostedtoolcache/Python/3.8.10/x64/b
                          in:/opt/hostedtoolcache/Python/3.8.10/x64:/home/linuxbrew/.linuxbrew/b
                          in:/home/linuxbrew/.linuxbrew/sbin:/home/runner/.local/bin:/opt/pipx_b
                          in:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin
                          :/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local
                          /sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/loc
                          al/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
        SELENIUM_JAR_PATH=/usr/share/java/selenium-server-standalone.jar
            SSL_CERT_FILE=<not set>
               SWIFT_PATH=/usr/share/swift/usr/bin
           pythonLocation=/opt/hostedtoolcache/Python/3.8.10/x64

     active environment : None
       user config file : /home/runner/.condarc
 populated config files : /home/runner/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/share/miniconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/runner/conda_pkgs_dir
       envs directories : /usr/share/miniconda/envs
                          /home/runner/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/5.8.0-1033-azure ubuntu/20.04.2 glibc/2.31
                UID:GID : 1001:121
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by ma-sadeghi** [comment]
Never mind, the error was from the CI machine. Fixed now.
