### ISSUE TITLE
Conda setup failing on creation in github CI workflow

### ISSUE THREAD

**Issue by jhdark** [conda-incubator/setup-miniconda#292]
Hi all, I can't seem to have conda working reliably in a github ci workflow, I assume it has something to do with using mamba too? I do need this to install a package later down the line. But, the initialisation seems to fail occasionally. Heres the .yml file I use and the error produced

```name: CI
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: myenv
        mamba-version: "*"
        channels: conda-forge, defaults
```

Error:
```Updating 'myenv' env from conda create (simple)...
  /usr/share/miniconda/condabin/mamba create --name myenv
  Warning: Traceback (most recent call last):
    File "/usr/share/miniconda/condabin/mamba", line 7, in <module>
  
  Traceback (most recent call last):
    File "/usr/share/miniconda/condabin/mamba", line 7, in <module>
  Warning:     from mamba.mamba import main
    File "/usr/share/miniconda/lib/python3.11/site-packages/mamba/mamba.py", line 49, in <module>
      import libmambapy as api
    File "/usr/share/miniconda/lib/python3.11/site-packages/libmambapy/__init__.py", line 7, in <module>
      raise e
    File "/usr/share/miniconda/lib/python3.11/site-packages/libmambapy/__init__.py", line 4, in <module>
      from libmambapy.bindings import *  # noqa: F401,F403
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ImportError: /usr/share/miniconda/lib/python3.11/site-packages/libmambapy/../../../libmamba.so.2: undefined symbol: solver_ruleinfo2str, version SOLV_1.0
  
      from mamba.mamba import main
    File "/usr/share/miniconda/lib/python3.11/site-packages/mamba/mamba.py", line 49, in <module>
      import libmambapy as api
    File "/usr/share/miniconda/lib/python3.11/site-packages/libmambapy/__init__.py", line 7, in <module>
      raise e
    File "/usr/share/miniconda/lib/python3.11/site-packages/libmambapy/__init__.py", line 4, in <module>
      from libmambapy.bindings import *  # noqa: F401,F403
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ImportError: /usr/share/miniconda/lib/python3.11/site-packages/libmambapy/../../../libmamba.so.2: undefined symbol: solver_ruleinfo2str, version SOLV_1.0

Error: The process '/usr/share/miniconda/condabin/mamba' failed with exit code 1```

**Comment by RemDelaporteMathurin** [comment]
The complete action run is available [here](https://github.com/RemDelaporteMathurin/FESTIM/actions/runs/6482522013/job/17602970755)

**Comment by tobiasdiez** [comment]
As a workaround, you can use mamba from miniforge by replacing `mamba-version: '*'` by 
```
          miniforge-version: latest
          use-mamba: true
          channels: conda-forge
```

**Comment by dlcaballero16** [comment]
So I am having a similar issue where I have an undefined symbol. According to [Mamba documentation](https://mamba.readthedocs.io/en/latest/user_guide/troubleshooting.html#using-the-defaults-channels), it does not like having the defaults channel included. When looking at the action on github, the defaults channel still gets added in the Applying Initial Configuration step, though not sure why. Hope this info helps.

**Comment by goanpeca** [comment]
Indeed, it seems the defaults channel might be still leaking. Will take a look
