### ISSUE TITLE
Python/Pip not setup correctly when using macos-latest

### ISSUE THREAD

**Issue by Licini** [conda-incubator/setup-miniconda#87]
When using `macos-latest`, the python and pip are not linked properly. For instance my workflow has specified:
```
- uses: conda-incubator/setup-miniconda@v1.7.0
        with:
          miniconda-version: "latest"
          activate-environment: cgal
          channels: conda-forge
          python-version: 3.7

- name: Install
        run: |
          pip install -r requirements-dev.txt 
          pip install -e .
```

However I'm getting an error:
```
Run pip install -r requirements-dev.txt 
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Obtaining file:///Users/runner/work/compas_cgal/compas_cgal (from -r requirements-dev.txt (line 18))
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@2.7.17/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/runner/work/compas_cgal/compas_cgal/setup.py'"'"'; __file__='"'"'/Users/runner/work/compas_cgal/compas_cgal/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /Users/runner/work/compas_cgal/compas_cgal/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/runner/work/compas_cgal/compas_cgal/setup.py", line 65, in <module>
        get_eigen_include(),
      File "/Users/runner/work/compas_cgal/compas_cgal/setup.py", line 43, in get_eigen_include
        return os.path.join(conda_prefix, 'include', 'eigen3')
      File "/usr/local/Cellar/python@2.7.17/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 70, in join
        elif path == '' or path.endswith('/'):
    AttributeError: 'NoneType' object has no attribute 'endswith'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Error: Process completed with exit code 1.
```
Seems it is still using the system python, instead of the one under conda

**Comment by bollwyvl** [comment]
The `shell` needs to be set, per step, and this can vary by os, to ensure
conda is activated. Each of the examples shows this, for various
platforms/shells.

>
If you're okay with one shell, e.g bash, you can use top level `defaults`,
however. Special care is needed for windows, as usual!

**Comment by Licini** [comment]
> The `shell` needs to be set, per step, and this can vary by os, to ensure conda is activated. Each of the examples shows this, for various platforms/shells.
> If you're okay with one shell, e.g bash, you can use top level `defaults`, however. Special care is needed for windows, as usual!

Thanks! it works after adding `shell: sh -l {0}`
